// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPlMstIwLG73POE1gzr5ZfQG12LNa4-QM',
    appId: '1:840621362166:web:d3920a4ec7bd23d4aa15d7',
    messagingSenderId: '840621362166',
    projectId: 'flash-chat-519a8',
    authDomain: 'flash-chat-519a8.firebaseapp.com',
    storageBucket: 'flash-chat-519a8.appspot.com',
    measurementId: 'G-2PQFSW5HCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA1gM7ASm2YYY0hn4Q9a7ex1YgLTokhW0',
    appId: '1:840621362166:android:7185d6cb3baf8f18aa15d7',
    messagingSenderId: '840621362166',
    projectId: 'flash-chat-519a8',
    storageBucket: 'flash-chat-519a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLJ_jjA1m9Y15XwBTRHU8oZnxZdPhUuQ',
    appId: '1:840621362166:ios:e76c15c082da5614aa15d7',
    messagingSenderId: '840621362166',
    projectId: 'flash-chat-519a8',
    storageBucket: 'flash-chat-519a8.appspot.com',
    iosBundleId: 'com.example.flashChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPlMstIwLG73POE1gzr5ZfQG12LNa4-QM',
    appId: '1:840621362166:web:dd6b3d6bf7d01771aa15d7',
    messagingSenderId: '840621362166',
    projectId: 'flash-chat-519a8',
    authDomain: 'flash-chat-519a8.firebaseapp.com',
    storageBucket: 'flash-chat-519a8.appspot.com',
    measurementId: 'G-MFCPB74X2M',
  );
}
